version: "3"
services:
  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=demotest
      - MYSQL_DATABASE=taskdb
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=test
  backend:
    image: backend
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/taskdb?useSSL=false
      - DB_USERNAME=sa
      - DB_PASSWORD=test
    networks:
      - springmysql-net
    depends_on:
      - mysqldb
  frontend:
    image: "frontend"
    container_name: "frontend"
    ports:
      - "80:80"
    networks:
      - springmysql-net
    depends_on:
      - backend
networks:
  springmysql-net: